export const resList = [
    {
      resName: "Domino's Pizza",
      resRating: 4.3,
      resETA: 27,
      cuisines: "Pizzas , Italians , Pastas , Desserts ",
      resLocation: "Punjabi Bagh",
      imgId: "bdyvrds2tuflpv5gor52",
    },
    {
      resName: "KFC",
      resRating: 4.3,
      resETA: 22,
      cuisines: "Burgers , Biryani , Snacks , Fast-food",
      resLocation: "Uttam Nagar",
      imgId: "f01666ac73626461d7455d9c24005cd4",
    },
    {
      resName: "Burger King",
      resRating: 4.4,
      resETA: 24,
      cuisines: "Burgers , American",
      resLocation: "Rajouri Garden",
      imgId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    },
    {
      resName: "McDonald's",
      resRating: 4.4,
      resETA: 32,
      cuisines: "American",
      resLocation: "Paschim Vihar",
      imgId: "6dc3ed2ca21d71acff7c2a51dfe4c720",
    },
    {
      resName: "Bakingo",
      resRating: 4.5,
      resETA: 24,
      cuisines: "Bakery , Desserts , Beverages , Snacks",
      resLocation: "Tagore Garden",
      imgId: "0c53fd8f62e3d25ba56d1b4cfe572cef",
    },
    {
      resName: "Pizza Hut",
      resRating: 4.1,
      resETA: 33,
      cuisines: "Pizzas",
      resLocation: "Rajouri Garden",
      imgId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
    },
    {
      resName: "La Pino'z Pizza",
      resRating: 4.1,
      resETA: 22,
      cuisines: "Pizzas , Pastas , Italian",
      resLocation: "Paschim Vihar",
      imgId: "tolejbnae10pq0udbavn",
    },
    {
      resName: "Stick Rice",
      resRating: 4.3,
      resETA: 23,
      cuisines: "Japanese , Asian",
      resLocation: "Punjabi Bagh",
      imgId: "rbaqe1fhtq3cyq8gycpj",
    },
    {
      resName: "Subway",
      resRating: 4.2,
      resETA: 29,
      cuisines: "Fast Food , Salads , Snacks",
      resLocation: "Paschim Vihar",
      imgId: "1ace5fa65eff3e1223feb696c956b38b",
    },
    {
      resName: "Pizza Hut",
      resRating: 4.8,
      resETA: 30,
      cuisines: "Pizzas",
      resLocation: "Uttam Nagar",
      imgId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
    },
  ];

